[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "DynamicDataCroissant"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mlcroissant = ">=1.0.17,<2"
